### ISSUE TITLE
User Story

### ISSUE THREAD

**Issue by Jxkeorton** [Jxkeorton/love-running#1]
In order to **give feedback** to the website owners, **i can** use the poll to select and submit my answers.

# Acceptance Criteria
* A clear layout must be provided 
* Checkboxes should be available next to the options
* A submit button should be below the options

# Tasks:

- [ ] Update the view: the poll design
- [ ] Create a new field in the model to track username
- [ ] update the controller function
- [ ] update unit test scripts
- [ ] test the functionality
